version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
